manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/ftc/
      # url-base: https://github.com/petejohanson
    - name: caksoylar
      url-base: https://github.com/caksoylar
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: mouse-ftc
      import: app/west.yml
    # - name: zmk
    #   remote: zmkfirmware
    #   revision: feat/pointers-move-scroll
    #   import: app/west.yml
    - name: zmk-rgbled-widget
      remote: caksoylar
      revision: main
  self:
    path: config
